"""next

Revision ID: 9a69f454ad53
Revises: c11f4cda7ba0
Create Date: 2023-03-22 12:57:35.452308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a69f454ad53'
down_revision = 'c11f4cda7ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('modify_layout', sa.Boolean(), nullable=False),
    sa.Column('modify_users_signup', sa.Boolean(), nullable=False),
    sa.Column('modify_users_comment', sa.Boolean(), nullable=False),
    sa.Column('modify_users_access', sa.Boolean(), nullable=False),
    sa.Column('modify_site_settings', sa.Boolean(), nullable=False),
    sa.Column('modify_site_access', sa.Boolean(), nullable=False),
    sa.Column('page_create', sa.Boolean(), nullable=False),
    sa.Column('page_update', sa.Boolean(), nullable=False),
    sa.Column('page_delete', sa.Boolean(), nullable=False),
    sa.Column('post_create', sa.Boolean(), nullable=False),
    sa.Column('post_update', sa.Boolean(), nullable=False),
    sa.Column('post_delete', sa.Boolean(), nullable=False),
    sa.Column('comment_create', sa.Boolean(), nullable=False),
    sa.Column('comment_update', sa.Boolean(), nullable=False),
    sa.Column('comment_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
